---
kind: pkgfile.Build
spec:
  targets:
    - sbc-raspberrypi
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
    - TOOLS_PREFIX
    - TOOLS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.12.0-32-g4f8efaf
      - name: TOOLS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: TOOLS
        defaultValue: v1.12.0
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
---
kind: common.Renovate
spec:
  packageRules:
    - matchPackageNames:
        - u-boot/u-boot
        - ARM-software/arm-trusted-firmware
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d+)\.?(?<patch>\d+)?$'
    - matchPackageNames:
        - raspberrypi/firmware
      versioning: 'regex:^\d+\.(?<major>\d{4})(?<minor>\d{2})(?<patch>\d{2})$'
